name: "Java Build and Vulnerability Scan"
description: "A reusable action to build a Java project and scan for vulnerabilities."

inputs:
  java-version:
    description: "The Java version to set up"
    required: true
    default: "17"
  scan-type:
    description: "The type of vulnerability scan to run"
    required: false
    default: "fs"
  docker-registry:
    description: "Docker registry for pushing images"
    required: true
  docker-tags:
    description: "Tags for the Docker image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn compile
      shell: bash

    - name: Test for Vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: ${{ inputs.scan-type }}

    - name: Log in to Docker Registry
      if: ${{ inputs.docker-registry }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.docker-password }}

    - name: Build and Push Docker Image
      if: ${{ inputs.docker-tags }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ inputs.docker-tags }}
