name: Build, Scan, and Push Docker Image
description: A composite action to build a Docker image, scan it with Trivy, and push it to a container registry.

inputs:
  image-name:
    description: The name of the Docker image (e.g., repo/image-name).
    required: true
  image-tags:
    description: The tag for the Docker image (e.g., latest).
    required: true
  docker-username:
    description: Docker registry username.
    required: true
  docker-password:
    description: Docker registry password.
    required: true
  docker-registry:
    description: "Docker registry for pushing images"
    required: false
    type: string
    default: "ghcr.io"


runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
        registry: ${{ inputs.docker-registry }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}

    - name: Scan Docker image
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ inputs.image-name }}:${{ inputs.image-tag }}
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        exit-code: 1

    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
